name: my_coding_setup
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

##############################################################################################################################
### Scripts
scripts:
  # run is a default script. To use it, simply type
  # in the command line: "rps" - that's all!
  model_build: "dart run build_runner build --delete-conflicting-outputs"
  pod: "cd ios && arch -x86_64 pod install && cd .."
  clean_get: "flutter clean && flutter pub get"

### Scripts
##############################################################################################################################
environment:
  sdk: '>=3.1.0 <4.0.0'
##############################################################################################################################
###
### Dependencies
###
dependencies:
  cookie_jar: ^4.0.8
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  envied: ^0.3.0+3
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  get_it: ^7.6.4
  injectable: ^2.3.0
  internet_connection_checker: ^1.0.0+1
  freezed_annotation: ^2.4.1
  rest_api_package: ^1.0.0+2
  stacked: ^3.4.1
  dio: ^5.4.1
  logger: ^2.1.0
  stacked_themes: ^0.3.12
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  intl: ^0.19.0

###
### Dependencies
###
##############################################################################################################################
##############################################################################################################################
###
### Dev Dependencies
###
dev_dependencies:
  build_runner: ^2.4.6

  ###
  ### Lint
  ###
  envied_generator: ^0.3.0+3
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter

  ###
  ### Injection Generator
  ###
  injectable_generator: ^2.4.0

  ###
  ### Json Serialization
  ###
  json_serializable: ^6.7.1
  freezed: ^2.4.1
  very_good_analysis: ^5.1.0
###
### Dev Dependencies
###
##############################################################################################################################
flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/logo/
    - assets/bank_logos/
    - assets/fonts/
    - test/fixtures/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Alibaba
      fonts:
        - asset: assets/fonts/AlibabaSans-Black.ttf
        - asset: assets/fonts/AlibabaSans-Black.otf
        - asset: assets/fonts/AlibabaSans-Bold.ttf
        - asset: assets/fonts/AlibabaSans-Bold.otf
        - asset: assets/fonts/AlibabaSans-Heavy.ttf
        - asset: assets/fonts/AlibabaSans-Heavy.otf
        - asset: assets/fonts/AlibabaSans-Light.ttf
        - asset: assets/fonts/AlibabaSans-Light.otf
        - asset: assets/fonts/AlibabaSans-Medium.ttf
        - asset: assets/fonts/AlibabaSans-Medium.otf
        - asset: assets/fonts/AlibabaSans-Regular.ttf
        - asset: assets/fonts/AlibabaSans-Regular.otf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
