// GENERATED CODE - DO WHATEVER YOU WANT WITH IT
// **************************************************************************
// Total assets: 40
// Generated by flutter_assets_generator extension for VS Code
// @mrasityilmaz
// **************************************************************************


class Assets {

	static const String b400100032_svg = 'assets/bank_logos/b400100032.svg';

	static const String b400100046_svg = 'assets/bank_logos/b400100046.svg';

	static const String b400100059_svg = 'assets/bank_logos/b400100059.svg';

	static const String b400100062_svg = 'assets/bank_logos/b400100062.svg';

	static const String b400100064_svg = 'assets/bank_logos/b400100064.svg';

	static const String b400100067_svg = 'assets/bank_logos/b400100067.svg';

	static const String b400100096_svg = 'assets/bank_logos/b400100096.svg';

	static const String b400100099_svg = 'assets/bank_logos/b400100099.svg';

	static const String b400100103_svg = 'assets/bank_logos/b400100103.svg';

	static const String b400100109_svg = 'assets/bank_logos/b400100109.svg';

	static const String b400100111_svg = 'assets/bank_logos/b400100111.svg';

	static const String b400100123_svg = 'assets/bank_logos/b400100123.svg';

	static const String b400100124_svg = 'assets/bank_logos/b400100124.svg';

	static const String b400100125_svg = 'assets/bank_logos/b400100125.svg';

	static const String b400100134_svg = 'assets/bank_logos/b400100134.svg';

	static const String b400100143_svg = 'assets/bank_logos/b400100143.svg';

	static const String b400100146_svg = 'assets/bank_logos/b400100146.svg';

	static const String b400101032_svg_svg = 'assets/bank_logos/b400101032.svg.svg';

	static const String b400101111_svg = 'assets/bank_logos/b400101111.svg';

	static const String b400200010_svg = 'assets/bank_logos/b400200010.svg';

	static const String b400200012_svg = 'assets/bank_logos/b400200012.svg';

	static const String b400200015_svg = 'assets/bank_logos/b400200015.svg';

	static const String b400300203_svg = 'assets/bank_logos/b400300203.svg';

	static const String b400300205_svg = 'assets/bank_logos/b400300205.svg';

	static const String b400300206_svg = 'assets/bank_logos/b400300206.svg';

	static const String b400300209_svg = 'assets/bank_logos/b400300209.svg';

	static const String b400300211_svg = 'assets/bank_logos/b400300211.svg';

	static const String alibabasans_black_otf = 'assets/fonts/AlibabaSans-Black.otf';

	static const String alibabasans_black_ttf = 'assets/fonts/AlibabaSans-Black.ttf';

	static const String alibabasans_bold_otf = 'assets/fonts/AlibabaSans-Bold.otf';

	static const String alibabasans_bold_ttf = 'assets/fonts/AlibabaSans-Bold.ttf';

	static const String alibabasans_heavy_otf = 'assets/fonts/AlibabaSans-Heavy.otf';

	static const String alibabasans_heavy_ttf = 'assets/fonts/AlibabaSans-Heavy.ttf';

	static const String alibabasans_light_otf = 'assets/fonts/AlibabaSans-Light.otf';

	static const String alibabasans_light_ttf = 'assets/fonts/AlibabaSans-Light.ttf';

	static const String alibabasans_medium_otf = 'assets/fonts/AlibabaSans-Medium.otf';

	static const String alibabasans_medium_ttf = 'assets/fonts/AlibabaSans-Medium.ttf';

	static const String alibabasans_regular_otf = 'assets/fonts/AlibabaSans-Regular.otf';

	static const String alibabasans_regular_ttf = 'assets/fonts/AlibabaSans-Regular.ttf';

	static const String tg_logo_svg = 'assets/logo/tg-logo.svg';

}
