// GENERATED CODE - DO WHATEVER YOU WANT WITH IT
// **************************************************************************
// Total assets: 24
// Generated by flutter_assets_generator extension for VS Code
// @mrasityilmaz
// **************************************************************************


class Assets {

	static const String b400100046_svg = 'assets/bank_logos/b400100046.svg';

	static const String b400100062_svg = 'assets/bank_logos/b400100062.svg';

	static const String b400100096_svg = 'assets/bank_logos/b400100096.svg';

	static const String b400100099_svg = 'assets/bank_logos/b400100099.svg';

	static const String b400100111_svg = 'assets/bank_logos/b400100111.svg';

	static const String b400100125_svg = 'assets/bank_logos/b400100125.svg';

	static const String b400101111_svg = 'assets/bank_logos/b400101111.svg';

	static const String b400200015_svg = 'assets/bank_logos/b400200015.svg';

	static const String b400300205_svg = 'assets/bank_logos/b400300205.svg';

	static const String b400300206_svg = 'assets/bank_logos/b400300206.svg';

	static const String b400300211_svg = 'assets/bank_logos/b400300211.svg';

	static const String alibabasans_black_otf = 'assets/fonts/AlibabaSans-Black.otf';

	static const String alibabasans_black_ttf = 'assets/fonts/AlibabaSans-Black.ttf';

	static const String alibabasans_bold_otf = 'assets/fonts/AlibabaSans-Bold.otf';

	static const String alibabasans_bold_ttf = 'assets/fonts/AlibabaSans-Bold.ttf';

	static const String alibabasans_heavy_otf = 'assets/fonts/AlibabaSans-Heavy.otf';

	static const String alibabasans_heavy_ttf = 'assets/fonts/AlibabaSans-Heavy.ttf';

	static const String alibabasans_light_otf = 'assets/fonts/AlibabaSans-Light.otf';

	static const String alibabasans_light_ttf = 'assets/fonts/AlibabaSans-Light.ttf';

	static const String alibabasans_medium_otf = 'assets/fonts/AlibabaSans-Medium.otf';

	static const String alibabasans_medium_ttf = 'assets/fonts/AlibabaSans-Medium.ttf';

	static const String alibabasans_regular_otf = 'assets/fonts/AlibabaSans-Regular.otf';

	static const String alibabasans_regular_ttf = 'assets/fonts/AlibabaSans-Regular.ttf';

	static const String tg_logo_svg = 'assets/logo/tg-logo.svg';

}
