// GENERATED CODE - DO WHATEVER YOU WANT WITH IT
// **************************************************************************
// Total assets: 13
// Generated by flutter_assets_generator extension for VS Code
// @mrasityilmaz
// **************************************************************************


class Assets {

	static const String alibabasans_black_otf = 'assets/fonts/AlibabaSans-Black.otf';

	static const String alibabasans_black_ttf = 'assets/fonts/AlibabaSans-Black.ttf';

	static const String alibabasans_bold_otf = 'assets/fonts/AlibabaSans-Bold.otf';

	static const String alibabasans_bold_ttf = 'assets/fonts/AlibabaSans-Bold.ttf';

	static const String alibabasans_heavy_otf = 'assets/fonts/AlibabaSans-Heavy.otf';

	static const String alibabasans_heavy_ttf = 'assets/fonts/AlibabaSans-Heavy.ttf';

	static const String alibabasans_light_otf = 'assets/fonts/AlibabaSans-Light.otf';

	static const String alibabasans_light_ttf = 'assets/fonts/AlibabaSans-Light.ttf';

	static const String alibabasans_medium_otf = 'assets/fonts/AlibabaSans-Medium.otf';

	static const String alibabasans_medium_ttf = 'assets/fonts/AlibabaSans-Medium.ttf';

	static const String alibabasans_regular_otf = 'assets/fonts/AlibabaSans-Regular.otf';

	static const String alibabasans_regular_ttf = 'assets/fonts/AlibabaSans-Regular.ttf';

	static const String tg_logo_svg = 'assets/logo/tg-logo.svg';

}
